version: "3.8"

services:
  govee_api:
    container_name: busse-govee-api
    build: .
    ports:
      - 8989:8989
    restart: unless-stopped
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "8989", "main:app"]
